const peer=new Peer();let localStream=null,currentCall=null,currentConn=null,screenTrack=null;
const $=id=>document.getElementById(id);const toast=t=>{const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),2200)};
const myId=$('my-id'),statusText=$('status-text'),connectionStatus=$('connection-status'),localVideo=$('local-video'),remoteVideo=$('remote-video'),localCard=$('local-card'),remoteCard=$('remote-card'),emptyState=$('empty-state');
function setStatus(t,online=false){statusText.textContent=t;connectionStatus.textContent=t;$('chat-state').textContent=online?'online':'offline';$('chat-dot').classList.toggle('online',online)}
async function startMedia(){try{localStream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});localVideo.srcObject=localStream;setStatus('Pronto para conectar');}catch(e){setStatus('Permita câmera e microfone');toast('Permissão de câmera/microfone necessária')}}
function showCall(){emptyState.classList.add('hidden');localCard.classList.remove('hidden');remoteCard.classList.remove('hidden')}
function addMessage(text,me=false){const box=$('messages');box.querySelector('.welcome')?.remove();const d=document.createElement('div');d.className='msg';const now=new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});d.innerHTML=`<div class="msg-head"><span class="avatar">${me?'♥':'♡'}</span><b>${me?'Você':'Seu amor'}</b><time>${now}</time></div><div class="msg-body"></div>`;d.querySelector('.msg-body').textContent=text;box.appendChild(d);box.scrollTop=box.scrollHeight}
function openData(conn){currentConn=conn;$('chat-state').textContent='online';$('chat-dot').classList.add('online');conn.on('data',d=>{if(d?.type==='chat')addMessage(d.text,false)});conn.on('close',()=>{currentConn=null;$('chat-state').textContent='offline';$('chat-dot').classList.remove('online')})}
function bindCall(call){currentCall=call;showCall();setStatus('Em chamada • conexão privada',true);call.on('stream',s=>remoteVideo.srcObject=s);call.on('close',endCall);call.on('error',()=>{toast('A chamada foi interrompida');endCall()})}
function endCall(){if(screenTrack)stopShare();currentCall=null;remoteVideo.srcObject=null;remoteCard.classList.add('hidden');localCard.classList.add('hidden');emptyState.classList.remove('hidden');setStatus('Chamada encerrada')}
peer.on('open',id=>{myId.textContent=id;setStatus('Online • pronto para conectar')});peer.on('error',e=>toast('Erro de conexão: '+(e.type||'desconhecido')));peer.on('call',call=>{if(!localStream)return toast('Aguarde a câmera iniciar');call.answer(localStream);bindCall(call)});peer.on('connection',openData);
$('call-btn').onclick=()=>{const id=$('connect-id').value.trim();if(!id)return toast('Digite o código da outra pessoa');if(!localStream)return toast('Aguarde a câmera iniciar');if(id===peer.id)return toast('Esse código é o seu próprio código');const call=peer.call(id,localStream);bindCall(call);openData(peer.connect(id));};
$('hero-connect').onclick=()=>$('connect-id').focus();$('hero-copy').onclick=()=>$('copy-id').click();
$('mic-btn').onclick=()=>{const t=localStream?.getAudioTracks()[0];if(!t)return;t.enabled=!t.enabled;$('mic-btn').textContent=t.enabled?'🎙':'🔇';$('local-mic').textContent=t.enabled?'🎙':'🔇';toast(t.enabled?'Microfone ligado':'Microfone desligado')};
$('camera-btn').onclick=()=>{const t=localStream?.getVideoTracks()[0];if(!t)return;t.enabled=!t.enabled;$('camera-btn').textContent=t.enabled?'▣':'□';toast(t.enabled?'Câmera ligada':'Câmera desligada')};
$('share-screen-btn').onclick=async()=>{if(!currentCall)return toast('Conecte-se em uma chamada primeiro');try{const s=await navigator.mediaDevices.getDisplayMedia({video:true});screenTrack=s.getVideoTracks()[0];const sender=currentCall.peerConnection.getSenders().find(x=>x.track?.kind==='video');if(sender)await sender.replaceTrack(screenTrack);localVideo.srcObject=s;screenTrack.onended=stopShare;toast('Compartilhamento de tela iniciado')}catch(e){toast('Compartilhamento cancelado')}};
async function stopShare(){if(!screenTrack)return;const cam=localStream?.getVideoTracks()[0];const sender=currentCall?.peerConnection?.getSenders().find(x=>x.track?.kind==='video');if(sender&&cam)await sender.replaceTrack(cam);screenTrack=null;if(localStream)localVideo.srcObject=localStream}
$('hangup-btn').onclick=()=>{currentCall?.close();endCall()};
async function copyId(){if(!peer.id)return;try{await navigator.clipboard.writeText(peer.id);toast('Código copiado para a área de transferência')}catch{toast('Não foi possível copiar automaticamente')}}$('copy-id').onclick=copyId;$('copy-link').onclick=copyId;
$('message-form').onsubmit=e=>{e.preventDefault();const i=$('message-input'),t=i.value.trim();if(!t)return;addMessage(t,true);if(currentConn?.open)currentConn.send({type:'chat',text:t});else toast('Você está offline — mensagem só nesta sessão');i.value=''};
$('clear-chat').onclick=()=>{if(confirm('Limpar as mensagens desta sessão?')){$('messages').innerHTML='<div class="welcome"><div class="welcome-icon">♡</div><strong>Começa aqui.</strong><p>Este é o cantinho de vocês.</p></div>'}};
$('theme-btn').onclick=()=>{document.body.classList.toggle('light');toast('A aparência desta versão é otimizada para o tema escuro')};$('settings-btn').onclick=()=>toast('Configurações rápidas: tema e controles estão disponíveis na tela');
document.querySelectorAll('.channel').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.channel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const name=btn.dataset.channel;$('page-title').textContent=name;if(name==='chamada'){$('connect-id').focus();toast('Área de chamada selecionada')}else if(name==='memorias')toast('Memórias — espaço reservado para vocês')} });
$('side-search').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.channel').forEach(c=>c.style.display=c.textContent.toLowerCase().includes(q)?'flex':'none')};
window.addEventListener('beforeunload',()=>localStream?.getTracks().forEach(t=>t.stop()));startMedia();
